---
title: "Panorama energético  geotermia actual"
format: revealjs
---

# Panorama de energía y energía renovable

## Contribución del suministro total de energía primaria por fuente, 2025

## Distribución regional del suministro total de energía primaria, 2025

## Contribución de las energías renovables al suministro total de energía primaria, 2025

## Consumo de petróleo per cápita por región, 2025

## Contribución de la generación eléctrica por fuente, 2025

## Contribución de la generación eléctrica por región, 2025

## Total del consumo mundial por fuente de energía, 2020-2050

## Mayores importadores netos de combustibles fósiles, 2025

# Impacto ambiental del consumo de energía

## Emisiones de CO2 por fuente de energía, 2025

## Contribución estimada de gases de efecto invernadero (GEI)

## Impacto ambiental del consumo de energía

* Aumento de las emisiones de generación eléctrica entre 2000 y 2025: %
* Aumento de las emisiones de CO_2 entre 2000 y 2025: %

# Geotermia y otras fuentes de energía renovable

* Proyección de aumento de consumo de energía renovable entre 2020 y 2050: % / a
* Crecimiento proyectado de la energía nuclear:
* Proyección de contribución de combustibles fósicles para 2050: %
* Aumento de consumo de gas natural, cuál es el combustible fósil de mayor crecimiento: % / a

## Emisiones de CO_2

Comparación con formas convencionales de energía

